---
- hosts: linuxservers
  remote_user: ansible
  tasks:
  - name: "ensure apache is at the latest version"
    yum:
      name: httpd
      state: latest
    service:
      name: httpd
      state: started
